import tests.model_enum_test
import tests.profileview_test
import tests.transaction_history_test
import tests.signup_test
import tests.pwd_login_test
import tests.blackjack_play_test
import tests.blackjack_checkfunds_test
