"""Add item_type column in Store table.

Revision ID: 5f5902f02dbd
Revises: e806fe26f71b
Create Date: 2020-11-26 16:15:36.951410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5902f02dbd'
down_revision = 'e806fe26f71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_column('item_type')

    # ### end Alembic commands ###
