"""Add blackjack table

Revision ID: 824d25286708
Revises: e4562ead3284
Create Date: 2020-11-21 14:20:09.888610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824d25286708'
down_revision = 'e4562ead3284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blackjack',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deck', sa.String(length=1023), nullable=True),
    sa.Column('player_hand', sa.String(length=255), nullable=True),
    sa.Column('dealer_hand', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blackjack')
    # ### end Alembic commands ###
