"""Change columns in blackjack table.

Revision ID: 8ebe36aad333
Revises: 8fb162641509
Create Date: 2020-11-21 13:42:13.111231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ebe36aad333'
down_revision = '8fb162641509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blackjack', schema=None) as batch_op:
        batch_op.alter_column('dealer_hand',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('deck',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.String(length=1023),
               existing_nullable=True)
        batch_op.alter_column('player_hand',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blackjack', schema=None) as batch_op:
        batch_op.alter_column('player_hand',
               existing_type=sa.String(length=255),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
        batch_op.alter_column('deck',
               existing_type=sa.String(length=1023),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
        batch_op.alter_column('dealer_hand',
               existing_type=sa.String(length=255),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)

    # ### end Alembic commands ###
