"""Add blackjack table.

Revision ID: 8fb162641509
Revises: e4562ead3284
Create Date: 2020-11-21 12:42:51.833092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb162641509'
down_revision = 'e4562ead3284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blackjack',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deck', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('player_hand', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('dealer_hand', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blackjack')
    # ### end Alembic commands ###
