"""Increase String size

Revision ID: e838d6ecadfd
Revises: 824d25286708
Create Date: 2020-11-21 23:12:17.374621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e838d6ecadfd'
down_revision = '824d25286708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blackjack', schema=None) as batch_op:
        batch_op.alter_column('deck',
               existing_type=sa.VARCHAR(length=1023),
               type_=sa.String(length=2047),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blackjack', schema=None) as batch_op:
        batch_op.alter_column('deck',
               existing_type=sa.String(length=2047),
               type_=sa.VARCHAR(length=1023),
               existing_nullable=True)

    # ### end Alembic commands ###
